<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Banner;

class BannerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Banner::truncate();

        $banners = [
            [
                'title' => 'Oyuncu Bilgisayarları &',
                'subtitle' => 'Hazır Sistem İndirimleri',
                'description' => 'Intel Core & AMD Ryzen yeni nesil işlemcili, GeForce RTX 40/50 serisi ekran kartlı, tak-çalıştır test edilmiş hazır oyuncu kasalarında dev indirim fırsatları!',
                'top_badge_icon' => 'fa-gamepad',
                'top_badge_text' => '🎮 HAZIR SİSTEM DEV KAMPANYASI',
                'top_badge_color' => 'amber',
                'tag1_icon' => 'fa-solid fa-gamepad',
                'tag1_text' => 'Ultra FPS Performansı',
                'tag2_icon' => 'fa-solid fa-shield-halved',
                'tag2_text' => '3 Yıl Parça Garantisi',
                'tag3_icon' => 'fa-solid fa-truck-fast',
                'tag3_text' => 'Aynı Gün Kargo',
                'button_text' => 'Hazır Sistemleri Keşfet',
                'button_url' => '/urunler?category=masaustu-bilgisayar',
                'card_header' => 'AFI GAMING PC',
                'card_badge' => '%25 İNDİRİM',
                'card_title' => 'Intel i7 14700F + RTX 4070 Ti SUPER',
                'card_spec1' => '• 32GB DDR5 6000MHz RAM',
                'card_spec2' => '• 1TB NVMe M.2 SSD',
                'card_spec3' => '• 240mm Sıvı Soğutma Sistemli',
                'card_old_price' => '64.999 ₺',
                'card_price' => '48.999 ₺',
                'card_button_text' => 'Ürüne Git',
                'card_button_url' => '/urunler?category=masaustu-bilgisayar',
                'bg_gradient' => 'from-[#1a1103] via-[#140d02] to-[#090b10]',
                'glow_color' => 'amber',
                'watermark_text' => 'GAMING',
                'order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'En Hızlı SSD ve',
                'subtitle' => 'M.2 Depolama Çözümleri',
                'description' => 'Oyun yükleme ekranlarını ve dev dosya transferlerini anında sıfırlayın! PCIe 4.0 & 5.0 M.2 SSD ve yüksek hızlı depolama donanımlarında dev kampanya.',
                'top_badge_icon' => 'fa-bolt',
                'top_badge_text' => '⚡ 7500 MB/s M.2 NVMe GÜCÜ',
                'top_badge_color' => 'cyan',
                'tag1_icon' => 'fa-solid fa-bolt-lightning',
                'tag1_text' => '7500 MB/s Okuma Hızı',
                'tag2_icon' => 'fa-solid fa-temperature-arrow-down',
                'tag2_text' => 'Alüminyum Isı Dağıtıcı',
                'tag3_icon' => 'fa-solid fa-hard-drive',
                'tag3_text' => '1TB / 2TB / 4TB Kapasiteler',
                'button_text' => 'SSD Fırsatlarını Gör',
                'button_url' => '/urunler?search=SSD',
                'card_header' => 'NVMe HIGH SPEED',
                'card_badge' => 'GEN4 x4',
                'card_title' => 'Samsung & Kingston M.2 NVMe SSD',
                'card_spec1' => '• 7450 MB/s Okuma / 6900 MB/s Yazma',
                'card_spec2' => '• PS5 ve PC Tam Uyumlu',
                'card_spec3' => '• 5 Yıl Üretici Garantisi',
                'card_old_price' => '3.899 ₺',
                'card_price' => '2.799 ₺',
                'card_button_text' => 'Ürüne Git',
                'card_button_url' => '/urunler?search=SSD',
                'bg_gradient' => 'from-[#03181a] via-[#021214] to-[#090b10]',
                'glow_color' => 'cyan',
                'watermark_text' => 'NVMe M.2',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'title' => 'Yüksek Yenileme Hızlı',
                'subtitle' => 'Oyuncu Monitörleri',
                'description' => 'Fast IPS, Curved ve OLED ekran panelleri, G-Sync & FreeSync uyumu, ultra yüksek yenileme hızıyla rakiplerinizin önünde olun!',
                'top_badge_icon' => 'fa-desktop',
                'top_badge_text' => '🖥️ 180Hz - 240Hz / 0.5ms TEPKİ SÜRESİ',
                'top_badge_color' => 'blue',
                'tag1_icon' => 'fa-solid fa-bullseye',
                'tag1_text' => '0.5ms Ultra Düşük Gecikme',
                'tag2_icon' => 'fa-solid fa-palette',
                'tag2_text' => '%99 sRGB & HDR10 Desteği',
                'tag3_icon' => 'fa-solid fa-eye',
                'tag3_text' => 'EyeCare Flicker-Free Korumalı',
                'button_text' => 'Monitörleri Keşfet',
                'button_url' => '/urunler?search=Monit%C3%B6r',
                'card_header' => 'CURVED GAMING',
                'card_badge' => '240Hz',
                'card_title' => '27" 2K QHD 240Hz 0.5ms Curved',
                'card_spec1' => '• 2560x1440 QHD Çözünürlük',
                'card_spec2' => '• 1500R Kavisli IPS Panel',
                'card_spec3' => '• Ergonomik Yükseklik Ayarlı',
                'card_old_price' => '11.499 ₺',
                'card_price' => '8.999 ₺',
                'card_button_text' => 'Ürüne Git',
                'card_button_url' => '/urunler?search=Monit%C3%B6r',
                'bg_gradient' => 'from-[#0b0d26] via-[#080a1d] to-[#090b10]',
                'glow_color' => 'blue',
                'watermark_text' => '240Hz OLED',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'title' => 'Ekran Kartı Fırsatları &',
                'subtitle' => 'Dev Kampanyalar',
                'description' => 'Real-time Ray Tracing ışın izleme ve DLSS 3.5 / FSR 3 yapay zeka grafik teknolojili sıfır ve garantili ekran kartlarında kaçırılmayacak fiyatlar!',
                'top_badge_icon' => 'fa-fire',
                'top_badge_text' => '🔥 NVIDIA RTX & AMD RADEON',
                'top_badge_color' => 'red',
                'tag1_icon' => 'fa-solid fa-wand-magic-sparkles',
                'tag1_text' => '4K Full Ray Tracing',
                'tag2_icon' => 'fa-solid fa-brain',
                'tag2_text' => 'DLSS 3.5 AI Frame Gen',
                'tag3_icon' => 'fa-solid fa-fan',
                'tag3_text' => 'Sessiz Fan & Sıvı Soğutma',
                'button_text' => 'Ekran Kartlarını İncele',
                'button_url' => '/urunler?search=Ekran+Kart%C3%B1',
                'card_header' => 'GEFORCE RTX',
                'card_badge' => '16GB VRAM',
                'card_title' => 'RTX 4070 Ti SUPER 16GB OC',
                'card_spec1' => '• 16GB GDDR6X 256-Bit',
                'card_spec2' => '• DLSS 3.5 Yapay Zeka Desteği',
                'card_spec3' => '• Tri-Fan Gelişmiş Soğutma',
                'card_old_price' => '39.999 ₺',
                'card_price' => '33.499 ₺',
                'card_button_text' => 'Ürüne Git',
                'card_button_url' => '/urunler?search=Ekran+Kart%C3%B1',
                'bg_gradient' => 'from-[#1c080b] via-[#140608] to-[#090b10]',
                'glow_color' => 'red',
                'watermark_text' => 'GPU RTX',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'title' => 'Profesyonel Teknik Servis &',
                'subtitle' => 'Güvenlik Sistemleri',
                'description' => 'Masaüstü ve laptop bilgisayar bakımı, donanım onarımı, IP güvenlik kamerası kurulumu ve yerinde ücretsiz keşif hizmetimizle cihazlarınız güvende!',
                'top_badge_icon' => 'fa-shield-halved',
                'top_badge_text' => '🛡️ UZMAN TEKNİK EKİP & 7/24 DESTEK',
                'top_badge_color' => 'cyan',
                'tag1_icon' => 'fa-solid fa-magnifying-glass',
                'tag1_text' => 'Ücretsiz Yerinde Keşif',
                'tag2_icon' => 'fa-solid fa-wrench',
                'tag2_text' => 'Orijinal Yedek Parça',
                'tag3_icon' => 'fa-solid fa-clock',
                'tag3_text' => '24 Saatte Hızlı Onarım',
                'button_text' => 'Servis Talebi Oluştur',
                'button_url' => '/teknik-servis',
                'card_header' => 'IP KAMERA & SERVİS',
                'card_badge' => 'GÜVENİLİR',
                'card_title' => '7/24 Teknik Servis & Keşif',
                'card_spec1' => '• Termal Macun & Fan Bakımı',
                'card_spec2' => '• Anakart & GPU Tamiri',
                'card_spec3' => '• Gece Görüşlü IP Kamera Montajı',
                'card_old_price' => null,
                'card_price' => 'Ücretsiz Keşif',
                'card_button_text' => 'Talep Oluştur',
                'card_button_url' => '/teknik-servis',
                'bg_gradient' => 'from-[#05151e] via-[#041017] to-[#090b10]',
                'glow_color' => 'cyan',
                'watermark_text' => 'SERVICE 7/24',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'title' => 'Garantili İkinci El Donanım &',
                'subtitle' => 'Sistem Vitrini',
                'description' => 'Uzman ekibimizce 35 farklı stres testinden geçirilmiş, Afi Bilişim garantisi altında sunulan ikinci el laptop, ekran kartı ve bilgisayar kasaları.',
                'top_badge_icon' => 'fa-recycle',
                'top_badge_text' => '♻️ TEST EDİLMİŞ AFİ GÜVENCESİ',
                'top_badge_color' => 'emerald',
                'tag1_icon' => 'fa-solid fa-flask',
                'tag1_text' => '35 Nokta Stres Testi',
                'tag2_icon' => 'fa-solid fa-rotate-left',
                'tag2_text' => '30 Gün Birebir Değişim',
                'tag3_icon' => 'fa-solid fa-piggy-bank',
                'tag3_text' => "%40'a Varan Tasarruf",
                'button_text' => 'İkinci El Vitrinini İncele',
                'button_url' => '/ikinci-el',
                'card_header' => 'AFİ ONAYLI',
                'card_badge' => 'GARANTİLİ',
                'card_title' => 'Test Edilmiş İkinci El Sistemler',
                'card_spec1' => '• FurMark & MemTest Onaylı',
                'card_spec2' => '• Sıfırlanmış & Bakımı Yapılmış',
                'card_spec3' => '• Fatura & Afi Garanti Belgesi',
                'card_old_price' => null,
                'card_price' => 'Bütçe Dostu',
                'card_button_text' => 'Vitrini Gör',
                'card_button_url' => '/ikinci-el',
                'bg_gradient' => 'from-[#061c13] via-[#04150e] to-[#090b10]',
                'glow_color' => 'emerald',
                'watermark_text' => 'REFURBISHED',
                'order' => 6,
                'is_active' => true,
            ],
        ];

        foreach ($banners as $bannerData) {
            Banner::create($bannerData);
        }
    }
}
